{
  "workbench.colorTheme": "Default {{ mode_title }} Modern",
  "workbench.colorCustomizations": {
    "foreground": "{{ foreground }}",
    "descriptionForeground": "{{ color8 }}",
    "disabledForeground": "{{ color8 }}",
    "errorForeground": "{{ color1 }}",
    "icon.foreground": "{{ foreground }}",
    "focusBorder": "{{ accent }}",
    "selection.background": "{{ selection_background }}",
    "widget.border": "{{ color8 }}",
    "sash.hoverBorder": "{{ accent }}",

    "textLink.foreground": "{{ accent }}",
    "textLink.activeForeground": "{{ accent }}",
    "textPreformat.foreground": "{{ color6 }}",
    "textPreformat.background": "{{ color0 }}",
    "textCodeBlock.background": "{{ color0 }}",
    "textBlockQuote.background": "{{ color0 }}",
    "textBlockQuote.border": "{{ accent }}",
    "textSeparator.foreground": "{{ color8 }}",

    "editor.background": "{{ background }}",
    "editor.foreground": "{{ foreground }}",
    "editorLineNumber.foreground": "{{ color8 }}",
    "editorLineNumber.activeForeground": "{{ accent }}",
    "editorCursor.foreground": "{{ cursor }}",
    "editorCursor.background": "{{ background }}",
    "editor.selectionBackground": "{{ selection_background }}",
    "editor.inactiveSelectionBackground": "{{ selection_background }}60",
    "editor.selectionHighlightBackground": "{{ accent }}30",
    "editor.wordHighlightBackground": "{{ accent }}30",
    "editor.wordHighlightStrongBackground": "{{ accent }}45",
    "editor.findMatchBackground": "{{ accent }}60",
    "editor.findMatchHighlightBackground": "{{ accent }}30",
    "editor.findRangeHighlightBackground": "{{ accent }}20",
    "editor.hoverHighlightBackground": "{{ accent }}30",
    "editor.rangeHighlightBackground": "{{ accent }}20",
    "editor.symbolHighlightBackground": "{{ accent }}30",
    "editor.lineHighlightBackground": "{{ color0 }}",
    "editor.foldBackground": "{{ accent }}20",
    "editorWhitespace.foreground": "{{ color8 }}",
    "editorIndentGuide.background1": "{{ color0 }}",
    "editorIndentGuide.activeBackground1": "{{ color8 }}",
    "editorRuler.foreground": "{{ color0 }}",
    "editorCodeLens.foreground": "{{ color8 }}",
    "editorLightBulb.foreground": "{{ color3 }}",
    "editorLink.activeForeground": "{{ accent }}",
    "editorGhostText.foreground": "{{ color8 }}",
    "editorInlayHint.background": "{{ color0 }}",
    "editorInlayHint.foreground": "{{ color8 }}",
    "editorBracketMatch.background": "{{ accent }}30",
    "editorBracketMatch.border": "{{ accent }}",
    "editorBracketHighlight.foreground1": "{{ color3 }}",
    "editorBracketHighlight.foreground2": "{{ color5 }}",
    "editorBracketHighlight.foreground3": "{{ color4 }}",
    "editorBracketHighlight.foreground4": "{{ color6 }}",
    "editorBracketHighlight.foreground5": "{{ color2 }}",
    "editorBracketHighlight.foreground6": "{{ color13 }}",
    "editorBracketHighlight.unexpectedBracket.foreground": "{{ color1 }}",

    "editorGutter.background": "{{ background }}",
    "editorGutter.modifiedBackground": "{{ color3 }}",
    "editorGutter.addedBackground": "{{ color2 }}",
    "editorGutter.deletedBackground": "{{ color1 }}",
    "editorGutter.foldingControlForeground": "{{ color8 }}",
    "editorGutter.commentRangeForeground": "{{ color8 }}",
    "editorPane.background": "{{ background }}",
    "breadcrumb.background": "{{ background }}",
    "breadcrumb.foreground": "{{ color8 }}",
    "breadcrumb.focusForeground": "{{ foreground }}",
    "breadcrumb.activeSelectionForeground": "{{ foreground }}",
    "breadcrumbPicker.background": "{{ background }}",
    "editorStickyScroll.background": "{{ background }}",
    "editorStickyScrollGutter.background": "{{ background }}",
    "editorStickyScrollHover.background": "{{ color0 }}",

    "minimap.background": "{{ background }}",
    "minimap.findMatchHighlight": "{{ accent }}80",
    "minimap.selectionHighlight": "{{ accent }}60",
    "minimap.errorHighlight": "{{ color1 }}",
    "minimap.warningHighlight": "{{ color3 }}",
    "minimapSlider.background": "{{ color8 }}20",
    "minimapSlider.hoverBackground": "{{ color8 }}40",
    "minimapSlider.activeBackground": "{{ color8 }}60",
    "minimapGutter.addedBackground": "{{ color2 }}",
    "minimapGutter.modifiedBackground": "{{ color3 }}",
    "minimapGutter.deletedBackground": "{{ color1 }}",
    "editorOverviewRuler.background": "{{ background }}",
    "editorOverviewRuler.border": "{{ color0 }}",
    "editorOverviewRuler.findMatchForeground": "{{ accent }}80",
    "editorOverviewRuler.selectionHighlightForeground": "{{ accent }}60",
    "editorOverviewRuler.wordHighlightForeground": "{{ accent }}60",
    "editorOverviewRuler.bracketMatchForeground": "{{ accent }}",
    "editorOverviewRuler.addedForeground": "{{ color2 }}",
    "editorOverviewRuler.modifiedForeground": "{{ color3 }}",
    "editorOverviewRuler.deletedForeground": "{{ color1 }}",
    "editorOverviewRuler.errorForeground": "{{ color1 }}",
    "editorOverviewRuler.warningForeground": "{{ color3 }}",
    "editorOverviewRuler.infoForeground": "{{ color4 }}",

    "editorError.foreground": "{{ color1 }}",
    "editorWarning.foreground": "{{ color3 }}",
    "editorInfo.foreground": "{{ color4 }}",
    "editorHint.foreground": "{{ color6 }}",
    "problemsErrorIcon.foreground": "{{ color1 }}",
    "problemsWarningIcon.foreground": "{{ color3 }}",
    "problemsInfoIcon.foreground": "{{ color4 }}",

    "editorWidget.background": "{{ background }}",
    "editorWidget.foreground": "{{ foreground }}",
    "editorWidget.border": "{{ color8 }}",
    "editorWidget.resizeBorder": "{{ accent }}",
    "editorHoverWidget.background": "{{ background }}",
    "editorHoverWidget.foreground": "{{ foreground }}",
    "editorHoverWidget.border": "{{ color8 }}",
    "editorHoverWidget.statusBarBackground": "{{ color0 }}",
    "editorSuggestWidget.background": "{{ background }}",
    "editorSuggestWidget.foreground": "{{ foreground }}",
    "editorSuggestWidget.border": "{{ color8 }}",
    "editorSuggestWidget.highlightForeground": "{{ accent }}",
    "editorSuggestWidget.focusHighlightForeground": "{{ accent }}",
    "editorSuggestWidget.selectedBackground": "{{ selection_background }}",
    "editorSuggestWidget.selectedForeground": "{{ selection_foreground }}",
    "editorMarkerNavigation.background": "{{ background }}",
    "editorMarkerNavigationError.background": "{{ color1 }}",
    "editorMarkerNavigationWarning.background": "{{ color3 }}",
    "editorMarkerNavigationInfo.background": "{{ color4 }}",

    "diffEditor.insertedTextBackground": "{{ color2 }}20",
    "diffEditor.removedTextBackground": "{{ color1 }}20",
    "diffEditor.insertedLineBackground": "{{ color2 }}15",
    "diffEditor.removedLineBackground": "{{ color1 }}15",
    "diffEditorGutter.insertedLineBackground": "{{ color2 }}30",
    "diffEditorGutter.removedLineBackground": "{{ color1 }}30",
    "diffEditor.border": "{{ color0 }}",
    "diffEditor.diagonalFill": "{{ color0 }}",
    "merge.currentHeaderBackground": "{{ color2 }}40",
    "merge.currentContentBackground": "{{ color2 }}20",
    "merge.incomingHeaderBackground": "{{ color4 }}40",
    "merge.incomingContentBackground": "{{ color4 }}20",
    "merge.border": "{{ color8 }}",

    "peekView.border": "{{ accent }}",
    "peekViewEditor.background": "{{ background }}",
    "peekViewEditorGutter.background": "{{ background }}",
    "peekViewEditor.matchHighlightBackground": "{{ accent }}40",
    "peekViewResult.background": "{{ background }}",
    "peekViewResult.fileForeground": "{{ foreground }}",
    "peekViewResult.lineForeground": "{{ color8 }}",
    "peekViewResult.matchHighlightBackground": "{{ accent }}40",
    "peekViewResult.selectionBackground": "{{ selection_background }}",
    "peekViewResult.selectionForeground": "{{ selection_foreground }}",
    "peekViewTitle.background": "{{ color0 }}",
    "peekViewTitleLabel.foreground": "{{ foreground }}",
    "peekViewTitleDescription.foreground": "{{ color8 }}",

    "activityBar.background": "{{ background }}",
    "activityBar.foreground": "{{ foreground }}",
    "activityBar.inactiveForeground": "{{ color8 }}",
    "activityBar.border": "{{ color0 }}",
    "activityBar.activeBorder": "{{ accent }}",
    "activityBar.dropBorder": "{{ accent }}",
    "activityBarBadge.background": "{{ accent }}",
    "activityBarBadge.foreground": "{{ background }}",
    "activityBarTop.foreground": "{{ foreground }}",
    "activityBarTop.inactiveForeground": "{{ color8 }}",
    "activityBarTop.activeBorder": "{{ accent }}",

    "sideBar.background": "{{ background }}",
    "sideBar.foreground": "{{ foreground }}",
    "sideBar.border": "{{ color0 }}",
    "sideBar.dropBackground": "{{ accent }}20",
    "sideBarTitle.foreground": "{{ foreground }}",
    "sideBarSectionHeader.background": "{{ color0 }}",
    "sideBarSectionHeader.foreground": "{{ foreground }}",
    "sideBarSectionHeader.border": "{{ color0 }}",
    "sideBarStickyScroll.background": "{{ background }}",

    "list.activeSelectionBackground": "{{ selection_background }}",
    "list.activeSelectionForeground": "{{ selection_foreground }}",
    "list.inactiveSelectionBackground": "{{ color0 }}",
    "list.inactiveSelectionForeground": "{{ foreground }}",
    "list.focusBackground": "{{ selection_background }}",
    "list.focusForeground": "{{ selection_foreground }}",
    "list.hoverBackground": "{{ color0 }}",
    "list.hoverForeground": "{{ foreground }}",
    "list.highlightForeground": "{{ accent }}",
    "list.focusHighlightForeground": "{{ accent }}",
    "list.dropBackground": "{{ accent }}20",
    "list.errorForeground": "{{ color1 }}",
    "list.warningForeground": "{{ color3 }}",
    "list.filterMatchBackground": "{{ accent }}30",
    "list.filterMatchBorder": "{{ accent }}",
    "listFilterWidget.background": "{{ background }}",
    "listFilterWidget.outline": "{{ accent }}",
    "listFilterWidget.noMatchesOutline": "{{ color1 }}",
    "tree.indentGuidesStroke": "{{ color0 }}",
    "tree.inactiveIndentGuidesStroke": "{{ color0 }}",

    "editorGroup.border": "{{ color0 }}",
    "editorGroup.dropBackground": "{{ accent }}20",
    "editorGroup.emptyBackground": "{{ background }}",
    "editorGroupHeader.tabsBackground": "{{ background }}",
    "editorGroupHeader.tabsBorder": "{{ color0 }}",
    "editorGroupHeader.noTabsBackground": "{{ background }}",
    "tab.activeBackground": "{{ color0 }}",
    "tab.activeForeground": "{{ foreground }}",
    "tab.inactiveBackground": "{{ background }}",
    "tab.inactiveForeground": "{{ color8 }}",
    "tab.hoverBackground": "{{ color0 }}",
    "tab.hoverForeground": "{{ foreground }}",
    "tab.unfocusedActiveBackground": "{{ color0 }}",
    "tab.unfocusedActiveForeground": "{{ color8 }}",
    "tab.unfocusedInactiveForeground": "{{ color8 }}",
    "tab.activeBorderTop": "{{ accent }}",
    "tab.border": "{{ background }}",
    "tab.lastPinnedBorder": "{{ color8 }}",

    "statusBar.background": "{{ background }}",
    "statusBar.foreground": "{{ foreground }}",
    "statusBar.border": "{{ color0 }}",
    "statusBar.focusBorder": "{{ accent }}",
    "statusBar.noFolderBackground": "{{ background }}",
    "statusBar.noFolderForeground": "{{ foreground }}",
    "statusBar.debuggingBackground": "{{ accent }}",
    "statusBar.debuggingForeground": "{{ background }}",
    "statusBarItem.hoverBackground": "{{ color0 }}",
    "statusBarItem.activeBackground": "{{ color0 }}",
    "statusBarItem.prominentBackground": "{{ color0 }}",
    "statusBarItem.prominentForeground": "{{ foreground }}",
    "statusBarItem.remoteBackground": "{{ accent }}",
    "statusBarItem.remoteForeground": "{{ background }}",
    "statusBarItem.errorBackground": "{{ color1 }}",
    "statusBarItem.errorForeground": "{{ background }}",
    "statusBarItem.warningBackground": "{{ color3 }}",
    "statusBarItem.warningForeground": "{{ background }}",

    "titleBar.activeBackground": "{{ background }}",
    "titleBar.activeForeground": "{{ foreground }}",
    "titleBar.inactiveBackground": "{{ background }}",
    "titleBar.inactiveForeground": "{{ color8 }}",
    "titleBar.border": "{{ color0 }}",
    "menubar.selectionBackground": "{{ selection_background }}",
    "menubar.selectionForeground": "{{ selection_foreground }}",
    "menu.background": "{{ background }}",
    "menu.foreground": "{{ foreground }}",
    "menu.border": "{{ color8 }}",
    "menu.separatorBackground": "{{ color0 }}",
    "menu.selectionBackground": "{{ selection_background }}",
    "menu.selectionForeground": "{{ selection_foreground }}",
    "commandCenter.background": "{{ color0 }}",
    "commandCenter.foreground": "{{ foreground }}",
    "commandCenter.border": "{{ color0 }}",
    "commandCenter.activeBackground": "{{ color0 }}",
    "commandCenter.activeForeground": "{{ foreground }}",

    "panel.background": "{{ background }}",
    "panel.border": "{{ color8 }}",
    "panel.dropBorder": "{{ accent }}",
    "panelTitle.activeForeground": "{{ foreground }}",
    "panelTitle.inactiveForeground": "{{ color8 }}",
    "panelTitle.activeBorder": "{{ accent }}",
    "panelSection.border": "{{ color0 }}",
    "panelSectionHeader.background": "{{ color0 }}",
    "panelSectionHeader.foreground": "{{ foreground }}",
    "panelInput.border": "{{ color8 }}",

    "dropdown.background": "{{ color0 }}",
    "dropdown.listBackground": "{{ background }}",
    "dropdown.foreground": "{{ foreground }}",
    "dropdown.border": "{{ color8 }}",
    "input.background": "{{ color0 }}",
    "input.foreground": "{{ foreground }}",
    "input.border": "{{ color8 }}",
    "input.placeholderForeground": "{{ color8 }}",
    "inputOption.activeBackground": "{{ accent }}30",
    "inputOption.activeForeground": "{{ foreground }}",
    "inputOption.activeBorder": "{{ accent }}",
    "inputValidation.errorBackground": "{{ background }}",
    "inputValidation.errorForeground": "{{ color1 }}",
    "inputValidation.errorBorder": "{{ color1 }}",
    "inputValidation.warningBackground": "{{ background }}",
    "inputValidation.warningForeground": "{{ color3 }}",
    "inputValidation.warningBorder": "{{ color3 }}",
    "inputValidation.infoBackground": "{{ background }}",
    "inputValidation.infoForeground": "{{ color4 }}",
    "inputValidation.infoBorder": "{{ color4 }}",
    "checkbox.background": "{{ color0 }}",
    "checkbox.foreground": "{{ foreground }}",
    "checkbox.border": "{{ color8 }}",
    "keybindingLabel.background": "{{ color0 }}",
    "keybindingLabel.foreground": "{{ foreground }}",
    "keybindingLabel.border": "{{ color8 }}",
    "keybindingLabel.bottomBorder": "{{ color8 }}",
    "banner.background": "{{ color0 }}",
    "banner.foreground": "{{ foreground }}",
    "banner.iconForeground": "{{ accent }}",

    "quickInput.background": "{{ background }}",
    "quickInput.foreground": "{{ foreground }}",
    "quickInputTitle.background": "{{ color0 }}",
    "quickInputList.focusBackground": "{{ selection_background }}",
    "quickInputList.focusForeground": "{{ selection_foreground }}",
    "pickerGroup.border": "{{ color0 }}",
    "pickerGroup.foreground": "{{ accent }}",

    "notifications.background": "{{ background }}",
    "notifications.foreground": "{{ foreground }}",
    "notifications.border": "{{ color0 }}",
    "notificationCenter.border": "{{ color8 }}",
    "notificationCenterHeader.background": "{{ color0 }}",
    "notificationCenterHeader.foreground": "{{ foreground }}",
    "notificationToast.border": "{{ color8 }}",
    "notificationLink.foreground": "{{ accent }}",
    "notificationsErrorIcon.foreground": "{{ color1 }}",
    "notificationsWarningIcon.foreground": "{{ color3 }}",
    "notificationsInfoIcon.foreground": "{{ color4 }}",

    "button.background": "{{ accent }}",
    "button.foreground": "{{ background }}",
    "button.hoverBackground": "{{ accent }}",
    "button.secondaryBackground": "{{ color0 }}",
    "button.secondaryForeground": "{{ foreground }}",
    "button.border": "{{ accent }}",
    "badge.background": "{{ accent }}",
    "badge.foreground": "{{ background }}",
    "progressBar.background": "{{ accent }}",
    "extensionButton.prominentBackground": "{{ accent }}",
    "extensionButton.prominentForeground": "{{ background }}",
    "extensionButton.prominentHoverBackground": "{{ accent }}",
    "extensionBadge.remoteBackground": "{{ accent }}",
    "extensionBadge.remoteForeground": "{{ background }}",
    "extensionIcon.starForeground": "{{ color3 }}",
    "extensionIcon.verifiedForeground": "{{ color2 }}",

    "scrollbar.shadow": "{{ background }}",
    "scrollbarSlider.background": "{{ color8 }}20",
    "scrollbarSlider.hoverBackground": "{{ color8 }}40",
    "scrollbarSlider.activeBackground": "{{ color8 }}60",
    "toolbar.hoverBackground": "{{ color0 }}",
    "toolbar.activeBackground": "{{ color0 }}",

    "gitDecoration.modifiedResourceForeground": "{{ color3 }}",
    "gitDecoration.deletedResourceForeground": "{{ color1 }}",
    "gitDecoration.addedResourceForeground": "{{ color2 }}",
    "gitDecoration.renamedResourceForeground": "{{ color6 }}",
    "gitDecoration.untrackedResourceForeground": "{{ color2 }}",
    "gitDecoration.ignoredResourceForeground": "{{ color8 }}",
    "gitDecoration.conflictingResourceForeground": "{{ color1 }}",
    "gitDecoration.stageModifiedResourceForeground": "{{ color3 }}",
    "gitDecoration.stageDeletedResourceForeground": "{{ color1 }}",
    "gitDecoration.submoduleResourceForeground": "{{ color5 }}",

    "debugToolBar.background": "{{ color0 }}",
    "debugToolBar.border": "{{ color8 }}",
    "debugIcon.breakpointForeground": "{{ color1 }}",
    "debugIcon.breakpointDisabledForeground": "{{ color8 }}",
    "debugIcon.startForeground": "{{ color2 }}",
    "debugIcon.pauseForeground": "{{ color3 }}",
    "debugIcon.stopForeground": "{{ color1 }}",
    "debugConsole.infoForeground": "{{ color4 }}",
    "debugConsole.warningForeground": "{{ color3 }}",
    "debugConsole.errorForeground": "{{ color1 }}",
    "debugConsole.sourceForeground": "{{ color8 }}",
    "editor.stackFrameHighlightBackground": "{{ color3 }}20",
    "editor.focusedStackFrameHighlightBackground": "{{ color2 }}20",
    "testing.iconPassed": "{{ color2 }}",
    "testing.iconFailed": "{{ color1 }}",
    "testing.iconQueued": "{{ color3 }}",
    "testing.iconSkipped": "{{ color8 }}",

    "settings.headerForeground": "{{ foreground }}",
    "settings.modifiedItemIndicator": "{{ accent }}",
    "settings.focusedRowBackground": "{{ color0 }}",
    "settings.rowHoverBackground": "{{ color0 }}",
    "settings.dropdownBackground": "{{ color0 }}",
    "settings.dropdownForeground": "{{ foreground }}",
    "settings.dropdownBorder": "{{ color8 }}",
    "settings.textInputBackground": "{{ color0 }}",
    "settings.textInputForeground": "{{ foreground }}",
    "settings.textInputBorder": "{{ color8 }}",
    "settings.numberInputBackground": "{{ color0 }}",
    "settings.numberInputForeground": "{{ foreground }}",
    "settings.numberInputBorder": "{{ color8 }}",
    "settings.checkboxBackground": "{{ color0 }}",
    "settings.checkboxForeground": "{{ foreground }}",
    "settings.checkboxBorder": "{{ color8 }}",
    "welcomePage.background": "{{ background }}",
    "welcomePage.tileBackground": "{{ color0 }}",
    "welcomePage.tileHoverBackground": "{{ color0 }}",
    "welcomePage.tileBorder": "{{ color8 }}",
    "welcomePage.progress.background": "{{ color0 }}",
    "welcomePage.progress.foreground": "{{ accent }}",
    "walkThrough.embeddedEditorBackground": "{{ background }}",

    "symbolIcon.classForeground": "{{ color3 }}",
    "symbolIcon.constantForeground": "{{ color5 }}",
    "symbolIcon.enumeratorForeground": "{{ color3 }}",
    "symbolIcon.enumeratorMemberForeground": "{{ color4 }}",
    "symbolIcon.fieldForeground": "{{ color4 }}",
    "symbolIcon.functionForeground": "{{ color4 }}",
    "symbolIcon.interfaceForeground": "{{ color6 }}",
    "symbolIcon.keywordForeground": "{{ color5 }}",
    "symbolIcon.methodForeground": "{{ color4 }}",
    "symbolIcon.moduleForeground": "{{ foreground }}",
    "symbolIcon.propertyForeground": "{{ foreground }}",
    "symbolIcon.stringForeground": "{{ color2 }}",
    "symbolIcon.structForeground": "{{ color3 }}",
    "symbolIcon.typeParameterForeground": "{{ color3 }}",
    "symbolIcon.variableForeground": "{{ foreground }}",

    "terminal.background": "{{ background }}",
    "terminal.foreground": "{{ foreground }}",
    "terminal.border": "{{ color8 }}",
    "terminal.selectionBackground": "{{ selection_background }}",
    "terminalCursor.foreground": "{{ cursor }}",
    "terminalCursor.background": "{{ background }}",
    "terminal.tab.activeBorder": "{{ accent }}",
    "terminal.ansiBlack": "{{ color0 }}",
    "terminal.ansiRed": "{{ color1 }}",
    "terminal.ansiGreen": "{{ color2 }}",
    "terminal.ansiYellow": "{{ color3 }}",
    "terminal.ansiBlue": "{{ color4 }}",
    "terminal.ansiMagenta": "{{ color5 }}",
    "terminal.ansiCyan": "{{ color6 }}",
    "terminal.ansiWhite": "{{ color7 }}",
    "terminal.ansiBrightBlack": "{{ color8 }}",
    "terminal.ansiBrightRed": "{{ color9 }}",
    "terminal.ansiBrightGreen": "{{ color10 }}",
    "terminal.ansiBrightYellow": "{{ color11 }}",
    "terminal.ansiBrightBlue": "{{ color12 }}",
    "terminal.ansiBrightMagenta": "{{ color13 }}",
    "terminal.ansiBrightCyan": "{{ color14 }}",
    "terminal.ansiBrightWhite": "{{ color15 }}"
  },
  "editor.tokenColorCustomizations": {
    "textMateRules": [
      {
        "scope": ["comment", "punctuation.definition.comment"],
        "settings": { "foreground": "{{ color8 }}", "fontStyle": "italic" }
      },
      {
        "scope": ["string", "string.quoted", "punctuation.definition.string"],
        "settings": { "foreground": "{{ color2 }}" }
      },
      {
        "scope": ["constant.numeric", "constant.language", "constant.character"],
        "settings": { "foreground": "{{ color5 }}" }
      },
      {
        "scope": ["keyword", "keyword.control", "storage.type", "storage.modifier"],
        "settings": { "foreground": "{{ color5 }}" }
      },
      {
        "scope": ["keyword.operator"],
        "settings": { "foreground": "{{ color6 }}" }
      },
      {
        "scope": ["entity.name.function", "support.function", "meta.function-call"],
        "settings": { "foreground": "{{ color4 }}" }
      },
      {
        "scope": ["entity.name.type", "entity.name.class", "support.type", "support.class"],
        "settings": { "foreground": "{{ color3 }}" }
      },
      {
        "scope": ["variable", "variable.other", "meta.definition.variable"],
        "settings": { "foreground": "{{ foreground }}" }
      },
      {
        "scope": ["variable.parameter"],
        "settings": { "foreground": "{{ color6 }}" }
      },
      {
        "scope": ["entity.name.tag"],
        "settings": { "foreground": "{{ color1 }}" }
      },
      {
        "scope": ["entity.other.attribute-name"],
        "settings": { "foreground": "{{ color3 }}" }
      },
      {
        "scope": ["invalid", "invalid.illegal"],
        "settings": { "foreground": "{{ color1 }}" }
      },
      {
        "scope": ["markup.heading", "entity.name.section"],
        "settings": { "foreground": "{{ accent }}", "fontStyle": "bold" }
      }
    ]
  }
}
